title: Volodymyr Sokolov, Ph.D.
logo: /images/sokolov.png
description: ORCID: [0000-0002-9349-7946](https://orcid.org/0000-0002-9349-7946)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
