title: Volodymyr Sokolov, Ph.D.
description: CV and Publication List
logo: /images/sokolov.png
social:
  name: Research Accounts
  links:
    - https://orcid.org/0000-0002-9349-7946
    - https://www.scopus.com/authid/detail.uri?authorId=57208521755
    - https://www.webofscience.com/wos/author/record/400301

theme: jekyll-theme-minimal

show_downloads: false
google_analytics:
lang: en
timezone: Europe/Kyiv
tagline: CV
