title: Volodymyr Sokolov, Ph.D.
logo: /images/sokolov.png
description: [IEEE](https://ieeexplore.ieee.org/author/37089400752), [ACM](https://dl.acm.org/profile/99660030382), [SSRN](https://ssrn.com/author=3711409), [DBLP](https://dblp.org/pers/hd/s/Sokolov:Volodymyr)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
